--- #installing httpd 
- name: installing
  hosts: '{{myhosts}}'
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root
  connection: ssh
  gather_facts: '{{gather}}'
  vars:
    gather: true
    package: httpd
  tasks:
  - name: Install the indicated softwaer
    yum:
      name: '{{ package }}'
      state: latest
