--- installing httpd 
- hosts: '{{myhosts}}'
  remote_user: ansible
  become_method: sudo
  become_user: root
  connection: ssh
  gather_facts: '{{gather}}'
  vars:
    myhosts: local,myhost1,myhost2
    gather: yes
    pkg: httpd
  tasks:
  - name: Install the indicated softwaer
    yum:
      name: '{{ pkg }}'
      state: latest
