--- #installing httpd 
  -name: installing
  hosts: '{{myhosts}}'
  remote_user: ansible
  become_method: sudo
  become_user: root
  connection: ssh
  gather_facts: '{{gather}}'
  vars:
    myhosts: local
    gather: yes
    pkg: httpd
  tasks:
  - name: Install the indicated softwaer
    yum:
      name: '{{ pkg }}'
      state: latest
