--- installing httpd 
- name: Installing httpd
  hosts: '{{ hosts }}'
  remote_user: ansible
  become_method: sudo
  gather_facts: true
  connection: ssh
  vars:
  hosts: local,myhost1,myhost2
  tasks: 
  - name: Installing httpd
    yum: 
      name: httpd
      state: latest
