--- #installing httpd 
- name: installing
  hosts: myhost1
  remote_user: ansible
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: '{{gather}}'
  vars:
    gather: true
    package: httpd
  tasks:
  - name: Install the indicated softwaer
    yum:
      name: '{{ package }}'
      state: latest
